subject_id_col: patientid

patient:
  admission:
    code: HOSPITAL_ADMISSION
    time: col(first_admitted_at_time)
  sex:
    code:
      - SEX
      - col(sex)
    time: null
  birth:
    code: MEDS_BIRTH
    time: col(date_of_birth)
  death:
    code: MEDS_DEATH
    time: col(date_of_death)
  discharge:
    code: HOSPITAL_DISCHARGE
    time: col(date_of_discharge)

raw_stage/pharma_records_parquet:
  medication:
    code:
      - MEDICATION
      - col(Variable Name)
    time: col(givenat)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(givendose)
    text_value: col(Unit)

raw_stage/observation_tables:
  observation:
    code:
      - OBSERVATION
      - col(Variable Name)
      - col(Unit)
    time: col(datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(value)
    text_value: col(stringvalue)
